ALTER TABLE "XpEvent"
ADD COLUMN IF NOT EXISTS "programId" TEXT,
ADD COLUMN IF NOT EXISTS "moduleId" TEXT,
ADD COLUMN IF NOT EXISTS "chapterId" TEXT;

ALTER TABLE "UserBadge"
ADD COLUMN IF NOT EXISTS "programId" TEXT,
ADD COLUMN IF NOT EXISTS "moduleId" TEXT,
ADD COLUMN IF NOT EXISTS "chapterId" TEXT;


ALTER TABLE "XpEvent"
ADD CONSTRAINT "XpEvent_programId_fkey"
FOREIGN KEY ("programId")
REFERENCES "Program"("id")
ON DELETE NO ACTION
ON UPDATE CASCADE;

ALTER TABLE "XpEvent"
ADD CONSTRAINT "XpEvent_moduleId_fkey"
FOREIGN KEY ("moduleId")
REFERENCES "Module"("id")
ON DELETE NO ACTION
ON UPDATE CASCADE;

ALTER TABLE "XpEvent"
ADD CONSTRAINT "XpEvent_chapterId_fkey"
FOREIGN KEY ("chapterId")
REFERENCES "Chapter"("id")
ON DELETE NO ACTION
ON UPDATE CASCADE;


ALTER TABLE "UserBadge"
ADD CONSTRAINT "UserBadge_programId_fkey"
FOREIGN KEY ("programId")
REFERENCES "Program"("id")
ON DELETE NO ACTION
ON UPDATE CASCADE;

ALTER TABLE "UserBadge"
ADD CONSTRAINT "UserBadge_moduleId_fkey"
FOREIGN KEY ("moduleId")
REFERENCES "Module"("id")
ON DELETE NO ACTION
ON UPDATE CASCADE;

ALTER TABLE "UserBadge"
ADD CONSTRAINT "UserBadge_chapterId_fkey"
FOREIGN KEY ("chapterId")
REFERENCES "Chapter"("id")
ON DELETE NO ACTION
ON UPDATE CASCADE;